spring.application.name=sql-intro



spring.datasource.url=jdbc:postgresql://localhost:5432/kutuphane1
spring.datasource.username=postgres
spring.datasource.password=Mami1903-
spring.jpa.hibernate.ddl-auto=none